// <auto-generated />
namespace CustomerFeedback.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class is_viewd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(is_viewd));
        
        string IMigrationMetadata.Id
        {
            get { return "201401100943512_is_viewd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
